// 单因子规则种子数据 Part 2 - INCOME_SERVICING, FUNDS_DEPOSIT

export const SEED_DATA_PART2 = [
  // ==================== INCOME_SERVICING ====================
  // overtime_bonus
  {
    category: "INCOME_SERVICING",
    factor: "overtime_bonus",
    risk_level: "LOW",
    scenario: "regular",
    expert_reasoning: "经常性加班费/奖金（Regular OT/Bonus）可以被银行认可，通常按最近2年平均值计算。需要证明这是工作常态而非偶发。",
    solutions: "1. 提供2年工资单显示OT/Bonus历史\n2. 获取雇主信确认OT/Bonus是岗位常态\n3. 计算2年平均值作为收入\n4. 部分银行认可80-100%",
    friendly_lenders: ["CBA", "ANZ", "Westpac", "NAB"],
    avoid_lenders: [],
    friendly_lenders_reason: "四大银行对Regular OT/Bonus有完善的认可政策",
    avoid_lenders_reason: "",
    required_documents: ["2年工资单（显示OT/Bonus）", "雇主信确认OT性质", "YTD收入证明"],
    clarifying_questions: ["OT/Bonus是否每月都有?", "金额是否稳定?", "是否是岗位必要组成部分?"],
    confidence_level: "HIGH",
    source_notes: "银行标准政策",
  },
  {
    category: "INCOME_SERVICING",
    factor: "overtime_bonus",
    risk_level: "MEDIUM",
    scenario: "occasional",
    expert_reasoning: "偶尔性加班费/奖金不被完全认可，银行会打折计算或只认可部分。因为不能保证未来会持续获得。",
    solutions: "1. 主要依靠基本工资申请\n2. OT/Bonus作为补充可能认可50%\n3. 选择对偶尔性收入较宽松的银行\n4. 准备说明为何是偶尔性的",
    friendly_lenders: ["Macquarie", "ING"],
    avoid_lenders: ["Westpac"],
    friendly_lenders_reason: "Macquarie和ING对偶尔性收入有一定认可度",
    avoid_lenders_reason: "Westpac对非经常性收入较严格",
    required_documents: ["工资单", "雇主信", "历史收入记录"],
    clarifying_questions: ["OT/Bonus多久发一次?", "金额波动大吗?", "是否有可能变成常规性的?"],
    confidence_level: "MEDIUM",
    source_notes: "BDM反馈",
  },
  {
    category: "INCOME_SERVICING",
    factor: "overtime_bonus",
    risk_level: "HIGH",
    scenario: "one_off",
    expert_reasoning: "一次性奖金（如签约奖金、项目完成奖金）通常不被银行认可为收入，因为无法保证会再次获得。",
    solutions: "1. 不要将一次性奖金计入收入预期\n2. 一次性奖金可作为首付来源\n3. 专注于基本工资申请\n4. 如奖金已到账，作为存款证明",
    friendly_lenders: [],
    avoid_lenders: ["CBA", "ANZ", "Westpac", "NAB"],
    friendly_lenders_reason: "",
    avoid_lenders_reason: "所有银行不认可一次性奖金作为收入",
    required_documents: ["基本工资证明"],
    clarifying_questions: ["奖金是什么性质?", "是否已经到账?", "到账后是否可作为首付?"],
    confidence_level: "HIGH",
    source_notes: "银行标准政策",
  },

  // rental_income
  {
    category: "INCOME_SERVICING",
    factor: "rental_income",
    risk_level: "LOW",
    scenario: "existing_tenant",
    expert_reasoning: "现有租约的租金收入是最可靠的被动收入形式。银行通常认可80%的租金（扣除空置率和费用）。有租约证明收入稳定性。",
    solutions: "1. 提供当前租约复印件\n2. 提供物业管理报告或租金入账记录\n3. 银行会按估价报告的租金或实际租金取较低值\n4. 认可比例通常80%",
    friendly_lenders: ["CBA", "ANZ", "Westpac", "NAB", "Macquarie"],
    avoid_lenders: [],
    friendly_lenders_reason: "所有银行接受现有租约收入",
    avoid_lenders_reason: "",
    required_documents: ["租约复印件", "物业管理报告", "租金入账银行流水", "费率通知"],
    clarifying_questions: ["租约还剩多久?", "租客是否按时付租?", "是否通过物业管理公司?"],
    confidence_level: "HIGH",
    source_notes: "银行标准政策",
  },
  {
    category: "INCOME_SERVICING",
    factor: "rental_income",
    risk_level: "MEDIUM",
    scenario: "proposed_rental",
    expert_reasoning: "拟租金（Proposed Rental）是指还没有租出去的物业的预期租金。银行通常会用估价报告中的租金评估，认可比例较低（70-80%）。",
    solutions: "1. 获取估价报告中的租金评估\n2. 准备同区域租金比较数据\n3. 部分银行可能不认可Proposed Rental\n4. 认可比例通常低于现有租约",
    friendly_lenders: ["Macquarie", "ING", "Suncorp"],
    avoid_lenders: ["CBA"],
    friendly_lenders_reason: "这些银行对Proposed Rental有一定接受度",
    avoid_lenders_reason: "CBA对Proposed Rental较保守",
    required_documents: ["估价报告", "同区域租金数据", "物业详情"],
    clarifying_questions: ["物业是否已经可以出租?", "周边租金水平如何?", "是否有物业管理安排?"],
    confidence_level: "MEDIUM",
    source_notes: "银行政策差异",
  },
  {
    category: "INCOME_SERVICING",
    factor: "rental_income",
    risk_level: "MEDIUM",
    scenario: "rooming_house",
    expert_reasoning: "分租房（Rooming House）的租金收入结构复杂，银行通常只认可部分。需要证明合法合规经营，且收入计算方式与标准租赁不同。",
    solutions: "1. 提供所有房间的租约\n2. 证明Rooming House合规注册\n3. 银行可能只认可主租约或打折认可\n4. 选择对Rooming House有经验的银行",
    friendly_lenders: ["NAB", "Macquarie"],
    avoid_lenders: ["CBA", "Westpac"],
    friendly_lenders_reason: "NAB对Rooming House有一定经验",
    avoid_lenders_reason: "CBA和Westpac对非标准租赁较谨慎",
    required_documents: ["所有租约", "Rooming House注册证明", "物业合规证明", "收入记录"],
    clarifying_questions: ["Rooming House是否注册合规?", "有几个房间出租?", "空置率如何?"],
    confidence_level: "MEDIUM",
    source_notes: "BDM反馈",
  },
  {
    category: "INCOME_SERVICING",
    factor: "rental_income",
    risk_level: "HIGH",
    scenario: "airbnb",
    expert_reasoning: "Airbnb/短租收入波动大、季节性强，银行非常谨慎。大部分银行不认可或只认可很小比例。还涉及物业是否允许短租的问题。",
    solutions: "1. 大部分银行不认可Airbnb收入\n2. 如必须使用，提供12个月以上的收入记录\n3. 可能需要转为长租以获得银行认可\n4. 确认物业是否允许短租",
    friendly_lenders: ["Liberty", "Pepper Money"],
    avoid_lenders: ["CBA", "ANZ", "Westpac", "NAB"],
    friendly_lenders_reason: "Non-Prime Lender可能考虑Airbnb收入",
    avoid_lenders_reason: "Prime银行基本不认可Airbnb收入",
    required_documents: ["12个月Airbnb收入记录", "物业短租许可", "税务记录"],
    clarifying_questions: ["Airbnb经营多久了?", "收入是否稳定?", "物业是否允许短租?"],
    confidence_level: "HIGH",
    source_notes: "银行政策",
  },

  // hecs_help
  {
    category: "INCOME_SERVICING",
    factor: "hecs_help",
    risk_level: "LOW",
    scenario: "none",
    expert_reasoning: "无HECS/HELP债务是最理想状态，不影响Servicing计算。可以最大化借款能力。",
    solutions: "标准流程处理，无需额外考虑。",
    friendly_lenders: ["CBA", "ANZ", "Westpac", "NAB", "Macquarie", "ING"],
    avoid_lenders: [],
    friendly_lenders_reason: "所有银行欢迎无HECS债务的申请人",
    avoid_lenders_reason: "",
    required_documents: ["ATO账户确认无HECS"],
    clarifying_questions: [],
    confidence_level: "HIGH",
    source_notes: "标准政策",
  },
  {
    category: "INCOME_SERVICING",
    factor: "hecs_help",
    risk_level: "MEDIUM",
    scenario: "under_10k",
    expert_reasoning: "HECS余额在$10,000以下影响较小。银行会按ATO规定的还款比例计入负债，但金额不大，对借款能力影响有限。",
    solutions: "1. 银行自动计入HECS还款义务\n2. 如想最大化借款能力，可考虑一次性还清\n3. 对大部分申请影响不大",
    friendly_lenders: ["CBA", "ANZ", "Westpac", "NAB", "Macquarie", "ING"],
    avoid_lenders: [],
    friendly_lenders_reason: "小额HECS不影响申请",
    avoid_lenders_reason: "",
    required_documents: ["ATO账户显示HECS余额"],
    clarifying_questions: ["是否考虑一次性还清?"],
    confidence_level: "HIGH",
    source_notes: "标准政策",
  },
  {
    category: "INCOME_SERVICING",
    factor: "hecs_help",
    risk_level: "MEDIUM",
    scenario: "10k_to_30k",
    expert_reasoning: "HECS余额$10,000-$30,000会明显影响Servicing。银行按收入比例计算HECS还款（收入超过$51,550开始还款），这会减少可借金额。",
    solutions: "1. 了解HECS对借款能力的具体影响\n2. 如果差额不大，可考虑部分还款\n3. 接受借款能力可能减少$20,000-$50,000\n4. 选择HECS计算方式较友好的银行",
    friendly_lenders: ["Macquarie", "ING"],
    avoid_lenders: [],
    friendly_lenders_reason: "Macquarie和ING的HECS计算可能略微有利",
    avoid_lenders_reason: "",
    required_documents: ["ATO账户显示HECS余额", "收入证明"],
    clarifying_questions: ["是否了解HECS对借款能力的影响?", "是否愿意部分还款?"],
    confidence_level: "HIGH",
    source_notes: "银行Servicing计算",
  },
  {
    category: "INCOME_SERVICING",
    factor: "hecs_help",
    risk_level: "HIGH",
    scenario: "over_30k",
    expert_reasoning: "HECS余额超过$30,000会显著影响借款能力。按当前还款比例（收入$100k+约还7-8%），每年还款可达$7,000-$8,000，大幅减少可借金额。",
    solutions: "1. 评估HECS对借款能力的实际影响\n2. 如影响大，考虑用存款部分还清HECS\n3. 选择HECS计算较宽松的银行\n4. 接受借款能力可能减少$50,000-$100,000",
    friendly_lenders: ["Macquarie"],
    avoid_lenders: ["Westpac"],
    friendly_lenders_reason: "Macquarie对HECS的处理相对灵活",
    avoid_lenders_reason: "Westpac的HECS计算较严格",
    required_documents: ["ATO账户显示HECS余额", "收入证明"],
    clarifying_questions: ["是否了解具体影响金额?", "是否有能力部分还清?", "还款后首付是否足够?"],
    confidence_level: "HIGH",
    source_notes: "银行Servicing计算及BDM反馈",
  },

  // living_expenses
  {
    category: "INCOME_SERVICING",
    factor: "living_expenses",
    risk_level: "LOW",
    scenario: "above_hem",
    expert_reasoning: "申报生活费高于HEM基准说明申请人如实申报，不会触发银行的生活费审查。银行会按申报金额或HEM取较高值计算。",
    solutions: "按申报处理即可。如生活费过高影响借款能力，可审视是否有可削减项目。",
    friendly_lenders: ["CBA", "ANZ", "Westpac", "NAB", "Macquarie", "ING"],
    avoid_lenders: [],
    friendly_lenders_reason: "如实申报是所有银行期望的",
    avoid_lenders_reason: "",
    required_documents: ["生活费声明"],
    clarifying_questions: ["生活费是否有大额可变项目?"],
    confidence_level: "HIGH",
    source_notes: "标准政策",
  },
  {
    category: "INCOME_SERVICING",
    factor: "living_expenses",
    risk_level: "LOW",
    scenario: "at_hem",
    expert_reasoning: "申报生活费接近HEM基准是大部分申请人的情况。银行会按HEM或申报值取较高值，通常不会额外审查。",
    solutions: "标准流程处理。",
    friendly_lenders: ["CBA", "ANZ", "Westpac", "NAB", "Macquarie", "ING"],
    avoid_lenders: [],
    friendly_lenders_reason: "HEM附近是正常范围",
    avoid_lenders_reason: "",
    required_documents: ["生活费声明"],
    clarifying_questions: [],
    confidence_level: "HIGH",
    source_notes: "标准政策",
  },
  {
    category: "INCOME_SERVICING",
    factor: "living_expenses",
    risk_level: "MEDIUM",
    scenario: "below_hem",
    expert_reasoning: "申报生活费低于HEM会触发银行审查。银行会用HEM替代申报值，并可能要求解释为何生活费如此低。",
    solutions: "1. 银行会自动调高至HEM\n2. 准备合理解释（如与父母同住、无车等）\n3. 提供银行流水支持低生活费声明\n4. 不要故意低报以提高借款能力",
    friendly_lenders: ["Macquarie", "ING"],
    avoid_lenders: ["Westpac"],
    friendly_lenders_reason: "Macquarie和ING对低生活费解释接受度较高",
    avoid_lenders_reason: "Westpac对生活费审查较严",
    required_documents: ["生活费声明", "银行流水", "解释信（如适用）"],
    clarifying_questions: ["为什么生活费这么低?", "是否与人合住分摊?", "有无车贷等固定支出?"],
    confidence_level: "HIGH",
    source_notes: "银行政策及审查流程",
  },

  // child_maintenance
  {
    category: "INCOME_SERVICING",
    factor: "child_maintenance",
    risk_level: "LOW",
    scenario: "none",
    expert_reasoning: "无子女抚养费义务是最简单的情况，不影响Servicing计算。",
    solutions: "标准流程处理。",
    friendly_lenders: ["CBA", "ANZ", "Westpac", "NAB", "Macquarie", "ING"],
    avoid_lenders: [],
    friendly_lenders_reason: "无额外负债",
    avoid_lenders_reason: "",
    required_documents: [],
    clarifying_questions: [],
    confidence_level: "HIGH",
    source_notes: "标准政策",
  },
  {
    category: "INCOME_SERVICING",
    factor: "child_maintenance",
    risk_level: "STOP",
    scenario: "paying",
    expert_reasoning: "需支付子女抚养费是固定负债，银行必须计入Servicing。金额通常较大（每月数百到数千），会显著减少借款能力。部分银行还要求稳定支付历史。",
    solutions: "1. 如实申报抚养费金额\n2. 提供抚养费协议或法院令\n3. 展示按时支付记录\n4. 接受借款能力可能大幅减少",
    friendly_lenders: ["CBA", "ANZ", "Westpac", "NAB"],
    avoid_lenders: [],
    friendly_lenders_reason: "主流银行有成熟的抚养费处理流程",
    avoid_lenders_reason: "",
    required_documents: ["抚养费协议/法院令", "支付记录", "银行流水显示扣款"],
    clarifying_questions: ["每月支付多少?", "还需支付多久?", "是否通过Child Support Agency?"],
    confidence_level: "HIGH",
    source_notes: "银行政策",
  },
  {
    category: "INCOME_SERVICING",
    factor: "child_maintenance",
    risk_level: "LOW",
    scenario: "receiving",
    expert_reasoning: "收取子女抚养费可以作为收入，但银行通常只部分认可（50-80%），因为支付方可能违约。需要稳定收取历史。",
    solutions: "1. 提供至少6-12个月的收取记录\n2. 部分银行只认可50-80%\n3. 提供抚养费协议证明金额\n4. 作为补充收入而非主要收入",
    friendly_lenders: ["ANZ", "NAB", "Macquarie"],
    avoid_lenders: ["CBA"],
    friendly_lenders_reason: "ANZ和NAB对抚养费收入认可度较高",
    avoid_lenders_reason: "CBA对抚养费收入认可较保守",
    required_documents: ["抚养费协议", "12个月收款记录", "银行流水"],
    clarifying_questions: ["收取多久了?", "是否每次都按时收到?", "金额是否稳定?"],
    confidence_level: "MEDIUM",
    source_notes: "银行政策差异",
  },

  // ==================== FUNDS_DEPOSIT ====================
  // genuine_savings
  {
    category: "FUNDS_DEPOSIT",
    factor: "genuine_savings",
    risk_level: "LOW",
    scenario: "has_5_percent_3_months",
    expert_reasoning: "有5%真实存款且存满3个月是LVR>90%的标准要求。证明申请人有储蓄习惯，降低违约风险。所有银行接受。",
    solutions: "提供银行流水证明存款来源和时长即可。",
    friendly_lenders: ["CBA", "ANZ", "Westpac", "NAB", "Macquarie", "ING"],
    avoid_lenders: [],
    friendly_lenders_reason: "满足真实存款要求",
    avoid_lenders_reason: "",
    required_documents: ["3个月银行流水", "存款来源证明"],
    clarifying_questions: ["存款来源是什么?（工资/卖房/赠与）"],
    confidence_level: "HIGH",
    source_notes: "银行标准政策",
  },
  {
    category: "FUNDS_DEPOSIT",
    factor: "genuine_savings",
    risk_level: "MEDIUM",
    scenario: "rent_as_savings",
    expert_reasoning: "用租房记录代替真实存款是部分银行接受的替代方案。需要12个月的按时租金支付记录，证明申请人有按时还款的习惯。",
    solutions: "1. 提供12个月租金支付记录\n2. 最好通过银行转账或物业管理\n3. 不能有拖欠记录\n4. 选择接受租金作为真实存款替代的银行",
    friendly_lenders: ["CBA", "ANZ", "Macquarie"],
    avoid_lenders: ["Westpac"],
    friendly_lenders_reason: "CBA和ANZ接受租金记录作为真实存款替代",
    avoid_lenders_reason: "Westpac不接受租金替代真实存款",
    required_documents: ["12个月租金支付记录", "租约", "物业管理报告或银行流水"],
    clarifying_questions: ["租金是否按时支付?", "是通过什么方式支付?", "是否有拖欠记录?"],
    confidence_level: "HIGH",
    source_notes: "银行政策对比",
  },
  {
    category: "FUNDS_DEPOSIT",
    factor: "genuine_savings",
    risk_level: "STOP",
    scenario: "no_genuine_savings",
    expert_reasoning: "LVR>90%时无真实存款是严重问题。没有储蓄习惯的申请人被视为高违约风险。大部分银行会拒绝。",
    solutions: "1. 降低LVR至90%以下（不需要真实存款）\n2. 开始存款，等3个月后再申请\n3. 使用租金记录替代（如银行接受）\n4. 找担保人提供担保",
    friendly_lenders: [],
    avoid_lenders: ["CBA", "ANZ", "Westpac", "NAB"],
    friendly_lenders_reason: "",
    avoid_lenders_reason: "Prime银行要求LVR>90%时必须有真实存款",
    required_documents: [],
    clarifying_questions: ["是否可以降低LVR?", "是否有租金支付记录?", "是否可以等3个月?"],
    confidence_level: "HIGH",
    source_notes: "银行政策",
  },

  // gifted_funds
  {
    category: "FUNDS_DEPOSIT",
    factor: "gifted_funds",
    risk_level: "LOW",
    scenario: "none",
    expert_reasoning: "没有赠与资金，首付全部来自自有储蓄，是银行最喜欢的情况。",
    solutions: "标准流程处理。",
    friendly_lenders: ["CBA", "ANZ", "Westpac", "NAB", "Macquarie", "ING"],
    avoid_lenders: [],
    friendly_lenders_reason: "自有资金最受欢迎",
    avoid_lenders_reason: "",
    required_documents: ["首付来源证明"],
    clarifying_questions: [],
    confidence_level: "HIGH",
    source_notes: "标准政策",
  },
  {
    category: "FUNDS_DEPOSIT",
    factor: "gifted_funds",
    risk_level: "LOW",
    scenario: "non_refundable",
    expert_reasoning: "不可退还赠与（Non-refundable Gift）是银行接受的赠与形式。需要赠与人签署声明，确认资金是无条件赠与，不需要偿还。",
    solutions: "1. 赠与人签署Gift Letter\n2. 声明资金不可退还\n3. 提供赠与人身份证明\n4. 显示资金转账记录",
    friendly_lenders: ["CBA", "ANZ", "Westpac", "NAB", "Macquarie", "ING"],
    avoid_lenders: [],
    friendly_lenders_reason: "所有银行接受Non-refundable Gift",
    avoid_lenders_reason: "",
    required_documents: ["Gift Letter（赠与人签字）", "赠与人身份证明", "转账记录", "赠与人银行流水"],
    clarifying_questions: ["赠与人是什么关系?", "赠与人是否了解签署声明的法律效力?"],
    confidence_level: "HIGH",
    source_notes: "银行标准政策",
  },
  {
    category: "FUNDS_DEPOSIT",
    factor: "gifted_funds",
    risk_level: "HIGH",
    scenario: "repayable",
    expert_reasoning: "需偿还的「赠与」实际上是贷款，必须计入负债。这会影响Servicing计算，减少借款能力。银行对此非常敏感。",
    solutions: "1. 如实申报为贷款而非赠与\n2. 计入负债进行Servicing计算\n3. 如可能，改为不可退还赠与\n4. 确保贷款条款合理",
    friendly_lenders: [],
    avoid_lenders: ["CBA", "ANZ", "Westpac", "NAB"],
    friendly_lenders_reason: "",
    avoid_lenders_reason: "所有银行对隐性负债非常警惕",
    required_documents: ["贷款协议", "还款计划"],
    clarifying_questions: ["还款条款是什么?", "是否可以改为不可退还赠与?", "每月还款金额?"],
    confidence_level: "HIGH",
    source_notes: "银行政策",
  },

  // deposit_source
  {
    category: "FUNDS_DEPOSIT",
    factor: "deposit_source",
    risk_level: "LOW",
    scenario: "savings",
    expert_reasoning: "个人储蓄是最理想的首付来源。银行只需要看到资金来源清晰，逐步积累的过程。",
    solutions: "提供银行流水显示储蓄积累过程即可。",
    friendly_lenders: ["CBA", "ANZ", "Westpac", "NAB", "Macquarie", "ING"],
    avoid_lenders: [],
    friendly_lenders_reason: "储蓄是最受欢迎的首付来源",
    avoid_lenders_reason: "",
    required_documents: ["3-6个月银行流水"],
    clarifying_questions: [],
    confidence_level: "HIGH",
    source_notes: "标准政策",
  },
  {
    category: "FUNDS_DEPOSIT",
    factor: "deposit_source",
    risk_level: "LOW",
    scenario: "equity",
    expert_reasoning: "从现有房产中提取Equity作为首付是成熟投资者常用方式。银行完全接受，只需要估价和贷款批准。",
    solutions: "1. 获取现有房产估价\n2. 申请Equity Release或Top Up\n3. 计算可提取金额\n4. 两笔贷款可能在同一银行或不同银行",
    friendly_lenders: ["CBA", "ANZ", "Westpac", "NAB", "Macquarie"],
    avoid_lenders: [],
    friendly_lenders_reason: "所有银行接受Equity作为首付",
    avoid_lenders_reason: "",
    required_documents: ["现有房产估价", "现有贷款详情", "Equity Release批准"],
    clarifying_questions: ["现有房产还有多少Equity?", "是否已获得Equity Release批准?"],
    confidence_level: "HIGH",
    source_notes: "标准政策",
  },
  {
    category: "FUNDS_DEPOSIT",
    factor: "deposit_source",
    risk_level: "MEDIUM",
    scenario: "gift",
    expert_reasoning: "亲友赠与需要额外文件证明，但只要是不可退还赠与，银行接受度高。",
    solutions: "1. 准备Gift Letter\n2. 提供赠与人身份和财务证明\n3. 显示资金转账记录",
    friendly_lenders: ["CBA", "ANZ", "Westpac", "NAB", "Macquarie", "ING"],
    avoid_lenders: [],
    friendly_lenders_reason: "带有Gift Letter的赠与被接受",
    avoid_lenders_reason: "",
    required_documents: ["Gift Letter", "赠与人身份证明", "转账记录"],
    clarifying_questions: ["赠与人是什么关系?", "是否愿意签署Gift Letter?"],
    confidence_level: "HIGH",
    source_notes: "标准政策",
  },
  {
    category: "FUNDS_DEPOSIT",
    factor: "deposit_source",
    risk_level: "HIGH",
    scenario: "crypto",
    expert_reasoning: "加密货币收益作为首付来源非常复杂。银行难以验证资金来源，涉及AML风险。大部分银行不接受或要求资金已变现至少3个月。",
    solutions: "1. 将加密货币变现至银行账户\n2. 资金存放至少3-6个月\n3. 提供完整的交易记录\n4. 可能需要税务证明",
    friendly_lenders: ["Macquarie"],
    avoid_lenders: ["CBA", "Westpac"],
    friendly_lenders_reason: "Macquarie对加密货币来源有一定接受度",
    avoid_lenders_reason: "CBA和Westpac对加密货币来源非常谨慎",
    required_documents: ["交易所交易记录", "变现后银行流水", "税务记录（如有CGT）"],
    clarifying_questions: ["加密货币变现多久了?", "有完整的交易记录吗?", "是否有CGT obligation?"],
    confidence_level: "LOW",
    source_notes: "银行政策正在演变中",
  },
  {
    category: "FUNDS_DEPOSIT",
    factor: "deposit_source",
    risk_level: "HIGH",
    scenario: "overseas",
    expert_reasoning: "海外资金需要完整的资金链证明，涉及AML合规。银行需要看到资金从海外账户到澳洲账户的完整路径。",
    solutions: "1. 准备完整资金链证明\n2. 资金来源文件（如海外工资单、卖房合同）\n3. 外汇兑换记录\n4. 资金提前转入澳洲账户3-6个月",
    friendly_lenders: ["HSBC", "NAB", "Bank of China"],
    avoid_lenders: ["Westpac"],
    friendly_lenders_reason: "有国际业务的银行对海外资金更有经验",
    avoid_lenders_reason: "Westpac对海外资金审查非常严格",
    required_documents: ["海外资金来源证明", "外汇兑换记录", "国际转账记录", "澳洲银行流水"],
    clarifying_questions: ["资金来源具体是什么?", "是否有完整转账记录?", "资金转入澳洲多久了?"],
    confidence_level: "HIGH",
    source_notes: "AML合规要求",
  },
  {
    category: "FUNDS_DEPOSIT",
    factor: "deposit_source",
    risk_level: "STOP",
    scenario: "unexplained_cash",
    expert_reasoning: "无法解释来源的现金是AML红旗，银行不会接受。可能导致申请被拒并报告可疑交易。",
    solutions: "1. 必须找到并证明资金来源\n2. 如果确实无法解释，不要使用这笔资金\n3. 使用其他可证明来源的资金\n4. 寻求会计师或律师建议",
    friendly_lenders: [],
    avoid_lenders: ["所有银行"],
    friendly_lenders_reason: "",
    avoid_lenders_reason: "无法解释来源的资金是AML违规",
    required_documents: [],
    clarifying_questions: ["这笔钱具体从哪里来?", "有没有任何记录?", "是否可以不使用这笔资金?"],
    confidence_level: "HIGH",
    source_notes: "AML法规要求",
  },

  // large_deposits
  {
    category: "FUNDS_DEPOSIT",
    factor: "large_deposits",
    risk_level: "LOW",
    scenario: "none",
    expert_reasoning: "没有大额存入，资金逐步积累，是银行最喜欢看到的情况。资金来源清晰透明。",
    solutions: "标准流程处理。",
    friendly_lenders: ["CBA", "ANZ", "Westpac", "NAB", "Macquarie", "ING"],
    avoid_lenders: [],
    friendly_lenders_reason: "无需额外解释",
    avoid_lenders_reason: "",
    required_documents: ["银行流水"],
    clarifying_questions: [],
    confidence_level: "HIGH",
    source_notes: "标准政策",
  },
  {
    category: "FUNDS_DEPOSIT",
    factor: "large_deposits",
    risk_level: "MEDIUM",
    scenario: "explained",
    expert_reasoning: "有大额存入但可解释（如卖车、奖金、赠与、税务退款）需要提供证明文件。银行会审查但可接受。",
    solutions: "1. 提供大额存入的来源证明\n2. 文件需要与存入金额和时间匹配\n3. 常见可接受来源：卖车/卖房、奖金、赠与、税务退款、遗产",
    friendly_lenders: ["CBA", "ANZ", "Westpac", "NAB", "Macquarie", "ING"],
    avoid_lenders: [],
    friendly_lenders_reason: "有证明的大额存入可接受",
    avoid_lenders_reason: "",
    required_documents: ["来源证明（卖车合同/奖金工资单/Gift Letter等）", "银行流水"],
    clarifying_questions: ["这笔大额存入是什么来源?", "是否有书面证明?"],
    confidence_level: "HIGH",
    source_notes: "银行审查流程",
  },
  {
    category: "FUNDS_DEPOSIT",
    factor: "large_deposits",
    risk_level: "STOP",
    scenario: "unexplained",
    expert_reasoning: "无法解释来源的大额存入会触发AML审查，银行通常会拒绝申请。可能需要向AUSTRAC报告。",
    solutions: "1. 必须找到资金来源证明\n2. 如确实无法解释，考虑不使用这笔资金\n3. 咨询会计师是否有遗漏的收入记录\n4. 可能需要时间来解决",
    friendly_lenders: [],
    avoid_lenders: ["所有银行"],
    friendly_lenders_reason: "",
    avoid_lenders_reason: "无法解释的大额存入是AML风险",
    required_documents: [],
    clarifying_questions: ["能否回忆这笔钱的来源?", "是否有任何相关文件?", "是否可以不使用这笔资金?"],
    confidence_level: "HIGH",
    source_notes: "AML合规要求",
  },
];
