// 单因子规则种子数据 Part 3 - CREDIT_CHARACTER, COLLATERAL

export const SEED_DATA_PART3 = [
  // ==================== CREDIT_CHARACTER ====================
  // credit_score
  {
    category: "CREDIT_CHARACTER",
    factor: "credit_score",
    risk_level: "LOW",
    scenario: "excellent",
    expert_reasoning: "信用分>800（优秀）是最理想状态，说明申请人信用历史良好，还款习惯优秀。可以享受最优条件和最快审批。",
    solutions: "标准流程处理。可以争取最优利率和条件。",
    friendly_lenders: ["CBA", "ANZ", "Westpac", "NAB", "Macquarie", "ING"],
    avoid_lenders: [],
    friendly_lenders_reason: "优秀信用分受所有银行欢迎",
    avoid_lenders_reason: "",
    required_documents: ["授权银行查询信用报告"],
    clarifying_questions: [],
    confidence_level: "HIGH",
    source_notes: "标准政策",
  },
  {
    category: "CREDIT_CHARACTER",
    factor: "credit_score",
    risk_level: "LOW",
    scenario: "good",
    expert_reasoning: "信用分700-800（良好）是大部分申请人的情况，银行完全接受。不会影响审批或条件。",
    solutions: "标准流程处理。",
    friendly_lenders: ["CBA", "ANZ", "Westpac", "NAB", "Macquarie", "ING"],
    avoid_lenders: [],
    friendly_lenders_reason: "良好信用分被广泛接受",
    avoid_lenders_reason: "",
    required_documents: ["授权银行查询信用报告"],
    clarifying_questions: [],
    confidence_level: "HIGH",
    source_notes: "标准政策",
  },
  {
    category: "CREDIT_CHARACTER",
    factor: "credit_score",
    risk_level: "MEDIUM",
    scenario: "average",
    expert_reasoning: "信用分500-700（一般）会引起银行注意。可能有轻微信用问题历史，银行会仔细审查信用报告细节。",
    solutions: "1. 获取完整信用报告了解扣分原因\n2. 准备解释信说明任何负面记录\n3. 选择对信用分要求较低的银行\n4. 可能需要降低LVR",
    friendly_lenders: ["Macquarie", "ING", "Suncorp"],
    avoid_lenders: ["Westpac"],
    friendly_lenders_reason: "这些银行对一般信用分有一定容忍度",
    avoid_lenders_reason: "Westpac对信用分要求较高",
    required_documents: ["完整信用报告", "解释信（如有负面记录）"],
    clarifying_questions: ["知道信用分低的原因吗?", "是否有任何违约或拖欠?", "近期信用分有改善吗?"],
    confidence_level: "HIGH",
    source_notes: "银行政策",
  },
  {
    category: "CREDIT_CHARACTER",
    factor: "credit_score",
    risk_level: "STOP",
    scenario: "poor",
    expert_reasoning: "信用分<500（较差）表明有严重信用问题，Prime银行通常会拒绝。需要了解具体原因并考虑Non-Prime Lender。",
    solutions: "1. 获取完整信用报告了解问题所在\n2. 如有错误，向信用机构申诉\n3. 准备详细解释信\n4. 只能考虑Non-Prime Lender\n5. 可能需要时间修复信用",
    friendly_lenders: ["Pepper Money", "Liberty", "La Trobe", "Bluestone"],
    avoid_lenders: ["CBA", "ANZ", "Westpac", "NAB"],
    friendly_lenders_reason: "Non-Prime Lender专门服务信用受损客户",
    avoid_lenders_reason: "Prime银行不接受低信用分",
    required_documents: ["完整信用报告", "详细解释信", "信用修复证据"],
    clarifying_questions: ["信用分低的具体原因是什么?", "是否有违约或破产记录?", "最近有采取什么修复措施?"],
    confidence_level: "HIGH",
    source_notes: "银行政策",
  },

  // credit_enquiries
  {
    category: "CREDIT_CHARACTER",
    factor: "credit_enquiries",
    risk_level: "LOW",
    scenario: "none",
    expert_reasoning: "过去30天无信用查询是最理想状态，说明申请人没有同时申请多家贷款。",
    solutions: "标准流程处理。",
    friendly_lenders: ["CBA", "ANZ", "Westpac", "NAB", "Macquarie", "ING"],
    avoid_lenders: [],
    friendly_lenders_reason: "无额外查询最受欢迎",
    avoid_lenders_reason: "",
    required_documents: [],
    clarifying_questions: [],
    confidence_level: "HIGH",
    source_notes: "标准政策",
  },
  {
    category: "CREDIT_CHARACTER",
    factor: "credit_enquiries",
    risk_level: "LOW",
    scenario: "1_to_2",
    expert_reasoning: "过去30天有1-2次查询是正常的，可能是比价或其他合理原因。银行不会特别关注。",
    solutions: "如银行问起，简单解释是比价或合理原因即可。",
    friendly_lenders: ["CBA", "ANZ", "Westpac", "NAB", "Macquarie", "ING"],
    avoid_lenders: [],
    friendly_lenders_reason: "1-2次查询在正常范围内",
    avoid_lenders_reason: "",
    required_documents: [],
    clarifying_questions: ["这些查询是什么原因?"],
    confidence_level: "HIGH",
    source_notes: "标准政策",
  },
  {
    category: "CREDIT_CHARACTER",
    factor: "credit_enquiries",
    risk_level: "MEDIUM",
    scenario: "3_plus",
    expert_reasoning: "过去30天超过3次查询会引起银行警觉。可能暗示申请人被多家拒绝或财务紧张。需要解释原因。",
    solutions: "1. 准备解释信说明查询原因\n2. 如果是比价，提供证据\n3. 等待30天后查询记录淡化\n4. 选择对查询较宽松的银行",
    friendly_lenders: ["Macquarie", "ING"],
    avoid_lenders: ["Westpac", "CBA"],
    friendly_lenders_reason: "Macquarie和ING对查询较宽容",
    avoid_lenders_reason: "Westpac和CBA对多次查询较敏感",
    required_documents: ["解释信"],
    clarifying_questions: ["这些查询具体是什么?", "是否有被拒绝的记录?", "是否可以等30天后再申请?"],
    confidence_level: "HIGH",
    source_notes: "银行政策",
  },

  // defaults
  {
    category: "CREDIT_CHARACTER",
    factor: "defaults",
    risk_level: "LOW",
    scenario: "none",
    expert_reasoning: "无违约记录是理想状态，说明申请人有良好的还款习惯。",
    solutions: "标准流程处理。",
    friendly_lenders: ["CBA", "ANZ", "Westpac", "NAB", "Macquarie", "ING"],
    avoid_lenders: [],
    friendly_lenders_reason: "无违约记录最受欢迎",
    avoid_lenders_reason: "",
    required_documents: [],
    clarifying_questions: [],
    confidence_level: "HIGH",
    source_notes: "标准政策",
  },
  {
    category: "CREDIT_CHARACTER",
    factor: "defaults",
    risk_level: "MEDIUM",
    scenario: "telco_under_1k_paid",
    expert_reasoning: "电信/水电小额违约（<$1000）且已付清，部分银行可以接受。需要解释原因并证明已还清。这类违约通常是疏忽而非还款能力问题。",
    solutions: "1. 准备解释信说明违约原因\n2. 提供还清证明\n3. 选择对小额违约宽容的银行\n4. 可能需要降低LVR",
    friendly_lenders: ["ANZ", "NAB", "Macquarie", "ING"],
    avoid_lenders: ["Westpac"],
    friendly_lenders_reason: "ANZ和NAB对已付清的小额违约有一定接受度",
    avoid_lenders_reason: "Westpac对任何违约都很敏感",
    required_documents: ["信用报告", "还清证明", "解释信"],
    clarifying_questions: ["违约是什么原因?", "什么时候还清的?", "是否有其他违约?"],
    confidence_level: "HIGH",
    source_notes: "银行政策",
  },
  {
    category: "CREDIT_CHARACTER",
    factor: "defaults",
    risk_level: "HIGH",
    scenario: "telco_under_1k_unpaid",
    expert_reasoning: "电信/水电小额违约（<$1000）未付清，说明申请人对债务处理不积极。银行会担心未来贷款也可能违约。需要先还清。",
    solutions: "1. 立即还清违约金额\n2. 获取还清证明\n3. 准备解释信\n4. 可能需要等待一段时间让记录淡化\n5. 考虑Non-Prime Lender",
    friendly_lenders: ["Pepper Money", "Liberty"],
    avoid_lenders: ["CBA", "ANZ", "Westpac", "NAB"],
    friendly_lenders_reason: "Non-Prime Lender可能接受未清违约",
    avoid_lenders_reason: "Prime银行不接受未付清的违约",
    required_documents: ["信用报告", "还清计划或证明", "解释信"],
    clarifying_questions: ["为什么还没还清?", "什么时候可以还清?", "还清后是否可以等待再申请?"],
    confidence_level: "HIGH",
    source_notes: "银行政策",
  },
  {
    category: "CREDIT_CHARACTER",
    factor: "defaults",
    risk_level: "STOP",
    scenario: "financial_default",
    expert_reasoning: "金融机构违约（如信用卡、个人贷款违约）是最严重的Character问题。这直接反映借款人对金融债务的态度，Prime银行通常会拒绝。",
    solutions: "1. 首先还清所有违约\n2. 等待至少12-24个月\n3. 准备详细解释信\n4. 只能考虑Non-Prime Lender\n5. 接受更高利率",
    friendly_lenders: ["Pepper Money", "Liberty", "La Trobe", "Bluestone"],
    avoid_lenders: ["CBA", "ANZ", "Westpac", "NAB", "Macquarie"],
    friendly_lenders_reason: "Non-Prime Lender专门服务有信用问题的客户",
    avoid_lenders_reason: "Prime银行对金融违约零容忍",
    required_documents: ["完整信用报告", "还清证明", "详细解释信", "财务恢复证明"],
    clarifying_questions: ["违约金额是多少?", "什么原因导致违约?", "现在财务状况如何?"],
    confidence_level: "HIGH",
    source_notes: "银行政策",
  },

  // payday_lenders
  {
    category: "CREDIT_CHARACTER",
    factor: "payday_lenders",
    risk_level: "LOW",
    scenario: "none",
    expert_reasoning: "无Payday Lender记录是理想状态。说明申请人不需要依赖高利贷解决短期资金问题。",
    solutions: "标准流程处理。",
    friendly_lenders: ["CBA", "ANZ", "Westpac", "NAB", "Macquarie", "ING"],
    avoid_lenders: [],
    friendly_lenders_reason: "无Payday Lender记录最受欢迎",
    avoid_lenders_reason: "",
    required_documents: [],
    clarifying_questions: [],
    confidence_level: "HIGH",
    source_notes: "标准政策",
  },
  {
    category: "CREDIT_CHARACTER",
    factor: "payday_lenders",
    risk_level: "HIGH",
    scenario: "over_3_months_ago",
    expert_reasoning: "3个月前有Payday Lender记录是严重警告。四大银行通常直接拒绝，因为这反映财务管理能力差。记录会在信用报告中保留5年。",
    solutions: "1. 准备详细解释信说明当时情况\n2. 展示财务状况已改善\n3. 只能考虑Non-Prime Lender\n4. 接受更高利率\n5. 等待记录更久远后再尝试Prime银行",
    friendly_lenders: ["Pepper Money", "Liberty", "La Trobe"],
    avoid_lenders: ["CBA", "ANZ", "Westpac", "NAB"],
    friendly_lenders_reason: "Non-Prime Lender可能考虑",
    avoid_lenders_reason: "四大银行对Payday Lender记录零容忍",
    required_documents: ["信用报告", "详细解释信", "财务改善证明"],
    clarifying_questions: ["当时为什么需要Payday Loan?", "现在财务状况如何?", "是否已完全还清?"],
    confidence_level: "HIGH",
    source_notes: "银行政策及BDM明确反馈",
  },
  {
    category: "CREDIT_CHARACTER",
    factor: "payday_lenders",
    risk_level: "STOP",
    scenario: "recent",
    expert_reasoning: "近期有Payday Lender记录（3个月内）是最严重的红旗之一。说明申请人当前仍有财务困难，几乎没有银行会批准。",
    solutions: "1. 等待至少6个月后再申请\n2. 在此期间展示财务稳定\n3. 绝不要在此时申请贷款\n4. 如紧急需求，只能找Private Lender（利率极高）",
    friendly_lenders: [],
    avoid_lenders: ["所有银行包括Non-Prime"],
    friendly_lenders_reason: "",
    avoid_lenders_reason: "近期Payday Lender记录是最严重的负面因素",
    required_documents: [],
    clarifying_questions: ["什么原因需要Payday Loan?", "是否可以等待6个月后再申请?"],
    confidence_level: "HIGH",
    source_notes: "行业共识",
  },

  // ato_debt
  {
    category: "CREDIT_CHARACTER",
    factor: "ato_debt",
    risk_level: "LOW",
    scenario: "none",
    expert_reasoning: "无ATO欠款是理想状态，说明申请人税务合规。",
    solutions: "标准流程处理。提供ATO账户确认无欠款。",
    friendly_lenders: ["CBA", "ANZ", "Westpac", "NAB", "Macquarie", "ING"],
    avoid_lenders: [],
    friendly_lenders_reason: "税务合规是基本要求",
    avoid_lenders_reason: "",
    required_documents: ["ATO Account Summary或税务评估"],
    clarifying_questions: [],
    confidence_level: "HIGH",
    source_notes: "标准政策",
  },
  {
    category: "CREDIT_CHARACTER",
    factor: "ato_debt",
    risk_level: "HIGH",
    scenario: "payment_plan",
    expert_reasoning: "有ATO欠款但在还款计划中，银行会有顾虑但可能考虑。需要证明还款计划在正常执行，且不影响Servicing。",
    solutions: "1. 提供ATO还款计划确认\n2. 展示按时还款记录\n3. 将还款金额计入负债\n4. 选择对ATO欠款较宽容的银行\n5. 准备解释欠款原因",
    friendly_lenders: ["NAB", "Macquarie"],
    avoid_lenders: ["CBA", "Westpac"],
    friendly_lenders_reason: "NAB对有还款计划的ATO欠款有一定接受度",
    avoid_lenders_reason: "CBA和Westpac对ATO欠款较严格",
    required_documents: ["ATO还款计划确认", "还款记录", "解释信"],
    clarifying_questions: ["欠款金额是多少?", "每月还款多少?", "还款计划执行多久了?"],
    confidence_level: "MEDIUM",
    source_notes: "银行政策差异",
  },
  {
    category: "CREDIT_CHARACTER",
    factor: "ato_debt",
    risk_level: "STOP",
    scenario: "outstanding",
    expert_reasoning: "有未结清ATO欠款且无还款计划是严重问题。说明申请人不仅税务不合规，而且没有积极处理。Prime银行不会接受。",
    solutions: "1. 立即与ATO建立还款计划\n2. 或一次性还清欠款\n3. 等还款计划执行一段时间后再申请\n4. 只能考虑Non-Prime Lender",
    friendly_lenders: ["Pepper Money", "Liberty"],
    avoid_lenders: ["CBA", "ANZ", "Westpac", "NAB", "Macquarie"],
    friendly_lenders_reason: "Non-Prime Lender可能考虑",
    avoid_lenders_reason: "Prime银行不接受未处理的ATO欠款",
    required_documents: ["ATO账户状态", "还款计划（如正在设立）"],
    clarifying_questions: ["欠款金额是多少?", "为什么还没有建立还款计划?", "是否可以一次性还清?"],
    confidence_level: "HIGH",
    source_notes: "银行政策",
  },

  // bankruptcy
  {
    category: "CREDIT_CHARACTER",
    factor: "bankruptcy",
    risk_level: "LOW",
    scenario: "none",
    expert_reasoning: "无破产记录是理想状态。",
    solutions: "标准流程处理。",
    friendly_lenders: ["CBA", "ANZ", "Westpac", "NAB", "Macquarie", "ING"],
    avoid_lenders: [],
    friendly_lenders_reason: "无破产记录是基本要求",
    avoid_lenders_reason: "",
    required_documents: [],
    clarifying_questions: [],
    confidence_level: "HIGH",
    source_notes: "标准政策",
  },
  {
    category: "CREDIT_CHARACTER",
    factor: "bankruptcy",
    risk_level: "HIGH",
    scenario: "discharged_over_2_years",
    expert_reasoning: "破产解除超过2年，部分Non-Prime Lender可以考虑。需要展示财务已完全恢复，有稳定收入和良好信用重建记录。",
    solutions: "1. 提供破产解除证明\n2. 展示2年以来的财务恢复\n3. 证明有稳定收入\n4. 准备详细解释信\n5. 接受Non-Prime Lender和更高利率",
    friendly_lenders: ["Pepper Money", "Liberty", "La Trobe", "Bluestone"],
    avoid_lenders: ["CBA", "ANZ", "Westpac", "NAB"],
    friendly_lenders_reason: "Non-Prime Lender专门服务破产后客户",
    avoid_lenders_reason: "Prime银行通常要求解除5年以上",
    required_documents: ["破产解除证明", "近2年税务记录", "信用报告", "解释信"],
    clarifying_questions: ["破产具体什么时候解除?", "破产原因是什么?", "目前财务状况如何?"],
    confidence_level: "HIGH",
    source_notes: "Non-Prime Lender政策",
  },
  {
    category: "CREDIT_CHARACTER",
    factor: "bankruptcy",
    risk_level: "STOP",
    scenario: "discharged_under_2_years",
    expert_reasoning: "破产解除不足2年，几乎没有任何Lender会批准。这是最严重的信用事件，需要更多时间来重建信用。",
    solutions: "1. 等待解除满2年后再申请\n2. 在此期间积极重建信用\n3. 保持稳定收入和良好还款记录\n4. 如紧急需求，只能找Private Lender",
    friendly_lenders: [],
    avoid_lenders: ["所有银行"],
    friendly_lenders_reason: "",
    avoid_lenders_reason: "破产解除不足2年没有Lender接受",
    required_documents: [],
    clarifying_questions: ["破产什么时候解除?", "是否可以等到满2年?"],
    confidence_level: "HIGH",
    source_notes: "行业共识",
  },
  {
    category: "CREDIT_CHARACTER",
    factor: "bankruptcy",
    risk_level: "STOP",
    scenario: "current",
    expert_reasoning: "当前破产中是最严重的情况，法律上无法申请贷款。必须等到破产解除后才能考虑。",
    solutions: "1. 等待破产解除（通常3年）\n2. 与破产管理人配合完成流程\n3. 破产期间无法申请任何贷款",
    friendly_lenders: [],
    avoid_lenders: ["所有银行"],
    friendly_lenders_reason: "",
    avoid_lenders_reason: "破产期间法律禁止申请贷款",
    required_documents: [],
    clarifying_questions: ["破产什么时候开始?", "预计什么时候解除?"],
    confidence_level: "HIGH",
    source_notes: "法律规定",
  },

  // ==================== COLLATERAL ====================
  // apartment_size
  {
    category: "COLLATERAL",
    factor: "apartment_size",
    risk_level: "LOW",
    scenario: "over_50",
    expert_reasoning: "公寓面积>50sqm是银行普遍接受的标准。这种大小的公寓有良好的市场流动性和价值稳定性。",
    solutions: "标准流程处理。",
    friendly_lenders: ["CBA", "ANZ", "Westpac", "NAB", "Macquarie", "ING"],
    avoid_lenders: [],
    friendly_lenders_reason: ">50sqm被所有银行接受",
    avoid_lenders_reason: "",
    required_documents: ["物业合同或估价报告"],
    clarifying_questions: [],
    confidence_level: "HIGH",
    source_notes: "银行标准政策",
  },
  {
    category: "COLLATERAL",
    factor: "apartment_size",
    risk_level: "MEDIUM",
    scenario: "40_to_50",
    expert_reasoning: "公寓面积40-50sqm处于灰色地带。部分银行可接受但可能限制LVR，部分银行可能拒绝或需要额外审批。",
    solutions: "1. 选择接受40-50sqm公寓的银行\n2. 可能需要降低LVR至80%以下\n3. 确认物业是否有其他问题（如High Density区域）\n4. 获取完整估价报告",
    friendly_lenders: ["Macquarie", "ING", "Suncorp"],
    avoid_lenders: ["Westpac"],
    friendly_lenders_reason: "Macquarie和ING对中等面积公寓接受度较高",
    avoid_lenders_reason: "Westpac对小面积公寓限制较多",
    required_documents: ["估价报告（显示面积）", "Strata Plan"],
    clarifying_questions: ["面积是内部面积还是含阳台?", "物业位于什么区域?", "同楼是否有短租?"],
    confidence_level: "HIGH",
    source_notes: "银行政策差异",
  },
  {
    category: "COLLATERAL",
    factor: "apartment_size",
    risk_level: "STOP",
    scenario: "under_40",
    expert_reasoning: "公寓面积<40sqm被大部分银行视为不可接受的抵押物。这类物业流动性差、价值波动大、难以出售。Prime银行通常拒绝。",
    solutions: "1. Prime银行基本不接受\n2. 考虑Non-Prime Lender但利率高\n3. 需要大幅降低LVR（可能<60%）\n4. 考虑换一个更大的物业",
    friendly_lenders: ["Pepper Money", "Liberty"],
    avoid_lenders: ["CBA", "ANZ", "Westpac", "NAB"],
    friendly_lenders_reason: "Non-Prime Lender可能考虑但条件苛刻",
    avoid_lenders_reason: "Prime银行不接受<40sqm公寓",
    required_documents: ["估价报告", "Strata Plan"],
    clarifying_questions: ["确定面积是<40sqm吗?", "是否考虑其他物业?", "是否可以接受高利率?"],
    confidence_level: "HIGH",
    source_notes: "银行政策",
  },
  {
    category: "COLLATERAL",
    factor: "apartment_size",
    risk_level: "LOW",
    scenario: "not_apartment",
    expert_reasoning: "非公寓物业（House、Townhouse等）不受面积限制，通常更受银行欢迎。",
    solutions: "标准流程处理。",
    friendly_lenders: ["CBA", "ANZ", "Westpac", "NAB", "Macquarie", "ING"],
    avoid_lenders: [],
    friendly_lenders_reason: "House等物业类型更受欢迎",
    avoid_lenders_reason: "",
    required_documents: ["物业合同或估价报告"],
    clarifying_questions: [],
    confidence_level: "HIGH",
    source_notes: "标准政策",
  },

  // lvr
  {
    category: "COLLATERAL",
    factor: "lvr",
    risk_level: "LOW",
    scenario: "under_60",
    expert_reasoning: "LVR<60%是最保守的贷款比例，银行风险最低。可以享受最优利率，审批最快，条件最宽松。",
    solutions: "标准流程处理。可以争取最优条件。",
    friendly_lenders: ["CBA", "ANZ", "Westpac", "NAB", "Macquarie", "ING"],
    avoid_lenders: [],
    friendly_lenders_reason: "低LVR受所有银行欢迎",
    avoid_lenders_reason: "",
    required_documents: ["估价报告", "首付证明"],
    clarifying_questions: [],
    confidence_level: "HIGH",
    source_notes: "标准政策",
  },
  {
    category: "COLLATERAL",
    factor: "lvr",
    risk_level: "LOW",
    scenario: "60_to_80",
    expert_reasoning: "LVR 60-80%是大部分贷款的标准范围。无需LMI，条件标准，利率正常。",
    solutions: "标准流程处理。",
    friendly_lenders: ["CBA", "ANZ", "Westpac", "NAB", "Macquarie", "ING"],
    avoid_lenders: [],
    friendly_lenders_reason: "标准LVR范围被广泛接受",
    avoid_lenders_reason: "",
    required_documents: ["估价报告", "首付证明"],
    clarifying_questions: [],
    confidence_level: "HIGH",
    source_notes: "标准政策",
  },
  {
    category: "COLLATERAL",
    factor: "lvr",
    risk_level: "MEDIUM",
    scenario: "80_to_90",
    expert_reasoning: "LVR 80-90%需要支付LMI（贷款保险），这会增加成本。部分银行对特定职业可免LMI。申请条件比80%以下稍严格。",
    solutions: "1. 计算LMI成本\n2. 检查是否符合LMI免除条件（如医生、律师、会计师）\n3. LMI可以加到贷款本金或一次性支付\n4. 确保其他条件满足要求",
    friendly_lenders: ["CBA", "ANZ", "Westpac", "NAB", "Macquarie"],
    avoid_lenders: [],
    friendly_lenders_reason: "主流银行都提供80-90% LVR产品",
    avoid_lenders_reason: "",
    required_documents: ["估价报告", "首付证明", "LMI职业证明（如适用）"],
    clarifying_questions: ["职业是否符合LMI免除?", "LMI是否可以接受?", "是否可以增加首付降低LVR?"],
    confidence_level: "HIGH",
    source_notes: "银行标准政策",
  },
  {
    category: "COLLATERAL",
    factor: "lvr",
    risk_level: "HIGH",
    scenario: "90_to_95",
    expert_reasoning: "LVR 90-95%是高杠杆贷款，LMI成本显著增加。银行审批更严格，需要真实存款证明，可能限制物业类型和位置。",
    solutions: "1. 确保有5%真实存款（存满3个月）\n2. 计算高额LMI成本\n3. 选择对高LVR友好的银行\n4. 确保其他所有条件都优秀\n5. 可能需要排除某些物业类型",
    friendly_lenders: ["CBA", "ANZ", "NAB"],
    avoid_lenders: ["Westpac"],
    friendly_lenders_reason: "CBA和ANZ有较完善的高LVR产品",
    avoid_lenders_reason: "Westpac对高LVR限制较多",
    required_documents: ["估价报告", "真实存款证明", "完整收入证明"],
    clarifying_questions: ["有5%真实存款吗?", "可以接受高额LMI吗?", "物业是否符合高LVR要求?"],
    confidence_level: "HIGH",
    source_notes: "银行政策",
  },
  {
    category: "COLLATERAL",
    factor: "lvr",
    risk_level: "STOP",
    scenario: "over_95",
    expert_reasoning: "LVR>95%只有极少数情况可以实现（如担保人贷款、特殊政府计划）。常规申请不可能获批。",
    solutions: "1. 常规贷款不支持>95% LVR\n2. 考虑担保人贷款（如父母担保）\n3. 检查是否符合政府首房计划\n4. 增加首付降低LVR",
    friendly_lenders: [],
    avoid_lenders: ["所有银行（常规产品）"],
    friendly_lenders_reason: "",
    avoid_lenders_reason: "没有常规产品支持>95% LVR",
    required_documents: ["担保人材料（如适用）"],
    clarifying_questions: ["是否有担保人?", "是否符合政府首房计划?", "能否增加首付?"],
    confidence_level: "HIGH",
    source_notes: "银行政策",
  },

  // property_type
  {
    category: "COLLATERAL",
    factor: "property_type",
    risk_level: "LOW",
    scenario: "house",
    expert_reasoning: "独立屋（House）是银行最喜欢的抵押物类型。土地价值稳定，市场流动性好，维护风险低。",
    solutions: "标准流程处理。",
    friendly_lenders: ["CBA", "ANZ", "Westpac", "NAB", "Macquarie", "ING"],
    avoid_lenders: [],
    friendly_lenders_reason: "House是最受欢迎的物业类型",
    avoid_lenders_reason: "",
    required_documents: ["物业合同", "估价报告"],
    clarifying_questions: [],
    confidence_level: "HIGH",
    source_notes: "标准政策",
  },
  {
    category: "COLLATERAL",
    factor: "property_type",
    risk_level: "LOW",
    scenario: "townhouse",
    expert_reasoning: "联排别墅（Townhouse）被银行广泛接受。有独立产权和一定的土地成分，比公寓更受欢迎。",
    solutions: "标准流程处理。",
    friendly_lenders: ["CBA", "ANZ", "Westpac", "NAB", "Macquarie", "ING"],
    avoid_lenders: [],
    friendly_lenders_reason: "Townhouse被广泛接受",
    avoid_lenders_reason: "",
    required_documents: ["物业合同", "估价报告"],
    clarifying_questions: [],
    confidence_level: "HIGH",
    source_notes: "标准政策",
  },
  {
    category: "COLLATERAL",
    factor: "property_type",
    risk_level: "LOW",
    scenario: "apartment",
    expert_reasoning: "公寓（Apartment）被银行接受，但需要注意面积、位置、楼层数等限制。高密度区域或小面积公寓可能有限制。",
    solutions: "1. 确认面积符合要求（通常>40sqm）\n2. 检查是否在高密度限制区域\n3. 确认楼内短租比例\n4. 获取Strata报告",
    friendly_lenders: ["CBA", "ANZ", "Westpac", "NAB", "Macquarie", "ING"],
    avoid_lenders: [],
    friendly_lenders_reason: "标准公寓被接受",
    avoid_lenders_reason: "",
    required_documents: ["物业合同", "估价报告", "Strata Report"],
    clarifying_questions: ["面积多大?", "是否在高密度区域?", "楼内有Airbnb吗?"],
    confidence_level: "HIGH",
    source_notes: "银行政策",
  },
  {
    category: "COLLATERAL",
    factor: "property_type",
    risk_level: "MEDIUM",
    scenario: "off_the_plan",
    expert_reasoning: "楼花（Off-the-plan）存在估值风险，交付时市场可能变化导致估价低于合同价。银行审批更谨慎，部分限制LVR。",
    solutions: "1. 准备应对可能的估价短缺\n2. 预留额外资金\n3. 选择对楼花友好的银行\n4. 注意交付前银行预审批可能过期",
    friendly_lenders: ["CBA", "NAB", "Macquarie"],
    avoid_lenders: ["Westpac"],
    friendly_lenders_reason: "CBA和NAB对楼花有较好的产品",
    avoid_lenders_reason: "Westpac对楼花限制较多",
    required_documents: ["购房合同", "楼书", "开发商信息", "预计交付日期"],
    clarifying_questions: ["什么时候交付?", "开发商信誉如何?", "有没有准备额外资金?"],
    confidence_level: "HIGH",
    source_notes: "银行政策",
  },
  {
    category: "COLLATERAL",
    factor: "property_type",
    risk_level: "HIGH",
    scenario: "rural",
    expert_reasoning: "农村/偏远地区物业流动性差，估值困难，市场买家有限。银行通常限制LVR或要求额外条件。",
    solutions: "1. 选择在该区域有业务的银行\n2. 可能需要降低LVR至70%以下\n3. 确保物业有可比销售案例\n4. 考虑区域银行或Non-Prime Lender",
    friendly_lenders: ["Suncorp", "Bendigo Bank", "Rabobank"],
    avoid_lenders: ["CBA", "Westpac"],
    friendly_lenders_reason: "区域银行对农村物业更熟悉",
    avoid_lenders_reason: "大银行对农村物业很谨慎",
    required_documents: ["估价报告", "物业详情", "同区域销售案例"],
    clarifying_questions: ["距离最近城镇多远?", "有没有可比销售?", "物业用途是什么?"],
    confidence_level: "HIGH",
    source_notes: "银行政策",
  },
  {
    category: "COLLATERAL",
    factor: "property_type",
    risk_level: "HIGH",
    scenario: "commercial",
    expert_reasoning: "商业物业需要商业贷款产品，不能用住宅贷款。审批标准完全不同，利率更高，LVR更低。",
    solutions: "1. 申请商业贷款而非住宅贷款\n2. 准备商业计划和租约\n3. 接受更高利率和更低LVR\n4. 选择有商业贷款产品的银行",
    friendly_lenders: ["NAB", "Westpac", "ANZ"],
    avoid_lenders: [],
    friendly_lenders_reason: "大银行都有商业贷款部门",
    avoid_lenders_reason: "",
    required_documents: ["商业计划", "租约", "财务报表", "估价报告"],
    clarifying_questions: ["物业是纯商业还是混合用途?", "有没有租约?", "买入目的是什么?"],
    confidence_level: "HIGH",
    source_notes: "商业贷款政策",
  },
];
